# GitPod configuration for GenX Trading Platform

image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Environment
    init: |
      echo "Setting up environment..."
      # Copy the example environment file
      cp .env.example .env
      echo "Environment setup complete. Please configure your API keys in .env"
    command: |
      echo "Workspace is ready!"

  - name: Run Backend Server
    command: |
      uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  - name: Run Frontend Server
    command: |
      npm run dev

vscode:
  extensions:
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - bradlc.vscode-tailwindcss
    - ms-azuretools.vscode-docker

ports:
  - port: 8000
    onOpen: open-preview
    name: "Backend API"
  - port: 5173
    onOpen: open-browser
    name: "Frontend App"
  - port: 5432
    onOpen: ignore
    name: "PostgreSQL"
  - port: 6379
    onOpen: ignore
    name: "Redis"
  - port: 27017
    onOpen: ignore
    name: "MongoDB"
