repos:
-   repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.63.1
    hooks:
    -   id: trufflehog
        name: TruffleHog
        description: Detect secrets in your code.
        entry: trufflehog filesystem
        args: ["--fail"]
        stages: [commit]