steps:
  # Build the container image with better error handling
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-f'
      - 'Dockerfile.exness'
      - '-t'
      - 'gcr.io/$PROJECT_ID/genx-exness-ea:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/genx-exness-ea:latest'
      - '.'
    timeout: '1200s'
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/genx-exness-ea']
    timeout: '600s'
  
  # Deploy to Cloud Run (simplified)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'genx-exness-ea'
      - '--image=gcr.io/$PROJECT_ID/genx-exness-ea:latest'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=3600'
      - '--port=8080'
      - '--set-env-vars=BROKER=exness,TRADING_MODE=live,TRADING_ENV=production'
    timeout: '600s'

# Images to be pushed to registry
images:
  - 'gcr.io/$PROJECT_ID/genx-exness-ea:latest'
  - 'gcr.io/$PROJECT_ID/genx-exness-ea:$BUILD_ID'

# Build options
options:
  # Use cloud logging only (required for new service accounts)
  logging: CLOUD_LOGGING_ONLY
  # Use a more powerful machine for faster builds
  machineType: 'E2_HIGHCPU_8'
  # Set disk size for large builds
  diskSizeGb: '100'

# Overall build timeout
timeout: '2400s'  # 40 minutes

# Substitutions for flexibility
substitutions:
  _REGION: 'europe-west1'
  _SERVICE_NAME: 'genx-exness-ea'