steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA', '-f', 'Dockerfile.production', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - '${_SERVICE_NAME}'
    - '--image'
    - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'
    - '--region'
    - '${_REGION}'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'BUCKET_NAME=${_BUCKET_NAME}'
    - '--set-env-vars'
    - 'GCP_PROJECT_ID=$PROJECT_ID'
    - '--memory'
    - '2Gi'
    - '--cpu'
    - '1'
    - '--max-instances'
    - '10'

substitutions:
  _SERVICE_NAME: genx-amp-system
  _REGION: us-central1
  _BUCKET_NAME: ${PROJECT_ID}-amp-data

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'
