steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.exness', '-t', 'gcr.io/$PROJECT_ID/genx-exness-ea', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/genx-exness-ea']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'genx-exness-ea'
      - '--image'
      - 'gcr.io/$PROJECT_ID/genx-exness-ea'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'BROKER=exness,TRADING_MODE=live'

images:
  - 'gcr.io/$PROJECT_ID/genx-exness-ea'

# Fix for 2024 Cloud Build service account changes
serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/$PROJECT_NUMBER-compute@developer.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  # Add timeout to prevent hanging builds
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1'
    - 'CLOUDSDK_COMPUTE_REGION=europe-west1'

# Add timeout for the entire build
timeout: '1800s'
