name: genx-fx-trading
services:
- name: web
  source_dir: /
  github:
    repo: your-username/genx-fx-trading
    branch: main
  build_command: npm install && npm run build
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  envs:
  - key: NODE_ENV
    value: production
  - key: SECRET_KEY
    type: SECRET
  - key: JWT_SECRET
    type: SECRET
  - key: FXCM_ACCESS_TOKEN
    type: SECRET
  - key: LOG_LEVEL
    value: INFO

- name: api
  source_dir: /
  github:
    repo: your-username/genx-fx-trading
    branch: main
  build_command: pip install -r requirements.txt
  run_command: uvicorn api.main:app --host 0.0.0.0 --port 8000
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8000
  envs:
  - key: SECRET_KEY
    type: SECRET
  - key: FXCM_ACCESS_TOKEN
    type: SECRET
  - key: BYBIT_API_KEY
    type: SECRET
  - key: BYBIT_API_SECRET
    type: SECRET
  - key: LOG_LEVEL
    value: INFO
  - key: ENVIRONMENT
    value: production

databases:
- name: postgres
  engine: PG
  version: "15"
  
- name: redis
  engine: REDIS
  version: "7"