name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run tests
        env:
          PYTHONPATH: .
          EXNESS_LOGIN: "dummy_login"
          EXNESS_PASSWORD: "dummy_password"
          EXNESS_SERVER: "dummy_server"
          AMP_TOKEN: "dummy_token"
          FXCM_API_KEY: "dummy_key"
          FXCM_SECRET_KEY: "dummy_secret"
          GEMINI_API_KEY: "dummy_key"
          OPENAI_API_KEY: "dummy_key"
          ALPHA_VANTAGE_API_KEY: "dummy_key"
          NEWS_API_KEY: "dummy_key"
          POSTGRES_DB: "amp_trading"
          POSTGRES_USER: "amp_user"
          POSTGRES_PASSWORD: "amp_password"
          POSTGRES_HOST: "localhost"
          POSTGRES_PORT: "5432"
          REDIS_HOST: "localhost"
          REDIS_PORT: "6379"
          AMP_ENV: "test"
          LOG_LEVEL: "INFO"
          DEBUG: "false"
          API_PORT: "8000"
          GRAFANA_PORT: "3000"
          JWT_SECRET_KEY: "test-secret-key"
          DATABASE_URL: "postgresql://amp_user:amp_password@localhost:5432/amp_trading"
        run: |
          pytest
