name: Build & Push Docker Image

on:
  push:
    branches:
      - main
      - cursor/check-docker-and-container-registration-status-5116
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            mouyleng/mouy-leng:latest
            mouyleng/mouy-leng:${{ github.sha }}
            mouyleng/mouy-leng:${{ github.ref_name }}
